Repository smartcar/node-sdk, pull requests merged in 2018-07, with the labels that each got.

#55 chore(ci): drop support for node 4, add support for node 10
  .travis.yml
  package.json
Labels: Status: Needs Review, Type: Configuration

#57 fix(docs): rename index.md to readme.md
  doc/.template.hbs
  doc/readme.md
  package.json
Labels: Status: Needs Review, Type: Configuration

#58 fix(docs): Fix ReadMe SDK reference link
  README.md
Labels: Status: Needs Review

#56 Fix user agent header and include node.js version
  lib/util.js
  test/lib/util.js
  test/lib/vehicle.js
Labels: Priority: 2 - Medium, Status: Needs Review, Type: Bug, Type: Enhancement

#54 Added validation of auth client params
  lib/auth-client.js
  package.json
  test/lib/auth-client.js
Labels: Status: Needs Review, Type: Enhancement

#59 Make age optional
  lib/vehicle.js
  test/lib/vehicle.js
Labels: Status: Needs Review
